name: Create GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker build -t generator .
      - run: |
          rm -rf $PWD/docs
          docker run -v $PWD/docs:/src/site/public generator
      - run: |
         git config --global user.name 'Bot'
         git config --global user.email 'atorrescogollo@gmail.com'
         git add docs/ && git commit -m "Autodoc"
         git push
